# Prepare contigs for nf-damage inference
Lucia Winkler, 28.07.2025, 15.10.2025

based on create_fasta_contig_genus.ipynb and contigs_taxo.ipynb by Maxime Borry
## What this notebook does:
Input data: contig taxonomic annotation, unfiltered pydamage output from nf-core/MAG run

The notebook filters for genera that are more abundant in 95% of the TDM datasets than in extraction blanks, based on proportion of mapped reads

The notebook filters for contigs with min. 50x coverage

**selection of core genera:**

The notebook selects genera, that appear in >90% (min.55/60 samples) of the stalagmite sequence datasets after filtering 

The sequences of the selected contigs are extracted from assembly fastas and put into pseudo-bins ordered by genus and sample

Sample sheets for the nf-damage inference pipeline are generated.

**Selection of test genera**

The notebook selects genera, that appear in 50-54/60 of the stalagmite sequence datasets after filtering 

The sequences of the selected contigs are extracted from assembly fastas and put into pseudo-bins ordered by genus and sample

Sample sheets for the nf-damage inference pipeline are generated.

In [1]:
import pandas as pd
import os
import glob
import taxopy
import re
from pathlib import Path
#from scipy.stats import mannwhitneyu
from collections import defaultdict
from tqdm import tqdm
import pysam

### Functions

In [ ]:
"Read and concatenate contig taxonomic annotation"
# Configuration
DATA_PATH = '<pat to>/MMSeqs_Contig_Taxonomy'
TSV_PATTERN = os.path.join(DATA_PATH, '*.tsv')

# Columns of interest
COLUMN_MAP = {
    0: 'contig',
    1: 'taxID',
    2: 'rank',
    3: 'taxon '
}

def load_and_process_tsv(file_path):
    sample_name = os.path.splitext(os.path.basename(file_path))[0]
    df = pd.read_csv(file_path, sep='\t', header=None)
    df = df.assign(sample=sample_name)

    # Rename selected columns
    df = df.rename(columns=COLUMN_MAP)

    # Drop columns 0 to 8 (inclusive), except renamed ones
    keep_cols = list(COLUMN_MAP.values()) + ['sample']
    df = df[keep_cols]
    return df

In [3]:
"Add genus and species name to tax. annotation"
taxdb = taxopy.TaxDb()

def get_genus(taxid, taxdb=taxdb):
    try:
        _ = taxopy.Taxon(taxid, taxdb)
        if "genus" in _.rank_name_dictionary:
            g =  _.rank_name_dictionary['genus']
        else:
            g = None
        if "species" in _.rank_name_dictionary:
            s =  _.rank_name_dictionary['species']
        else:
            s = None
    except taxopy.exceptions.TaxidError:
        g = None
        s = None
    return g, s

In [ ]:
'read unfiltered pydamage results table'
# Configuration
BASE_DIR = Path('<path to>/PyDamage_Full/analyze')
RESULT_FILENAME = 'pydamage_results/pydamage_results.csv'

# Patterns to support both TDM and EXB formats
ASSEMBLY_REGEX = r"(TDM\d{3}|EXB\d{3}_A\d{4})"

def find_pydamage_files(base_dir: Path, result_filename: str):
    """Finds all pydamage result files in subfolders."""
    folders = [f for f in base_dir.iterdir() if f.is_dir()]
    result_paths = [(f.name, f / result_filename) for f in folders if (f / result_filename).exists()]
    return result_paths

def load_and_annotate(file_info):
    """Loads a CSV and adds 'sample' column."""
    name, path = file_info
    df = pd.read_csv(path, usecols=range(16))
    df['sample'] = name
    df = df.rename(columns={'reference': 'contig'})
    return df

def standardize_assembly_name(name):
    """Extracts TDMxxx or EXB080_Axxxx pattern."""
    match = re.search(ASSEMBLY_REGEX, name)
    return match.group(0) if match else name  # fallback to original name if no match

In [5]:
'Extract core contigs into fasta'
def create_fasta(df, sample, genus, in_fa, outdir):
    genus_out = genus.lower().replace(" ", "_")
    out_fa = os.path.join(outdir, f"{sample}_{genus_out}.fa")
    # print(genus, sample)
    contigs = df[(df['genus'] == genus) & (df['sample'] == sample)].contig.values
    # print(contigs)
    if len(contigs) > 0:
        with pysam.FastxFile(in_fa) as fin, open(out_fa, "w") as fout:
            for entry in fin:
                if entry.name in contigs:
                    fout.write(str(entry) + "\n")

### Load data

In [6]:
# Process all taxonomic annotation TSV files and concatenate into df
all_dfs = [load_and_process_tsv(f) for f in glob.glob(TSV_PATTERN)]
tax_df = pd.concat(all_dfs, ignore_index=True)

In [7]:
# add genus and species name to df
tax_df['genus'], tax_df['species'] =  zip(*tax_df['taxID'].map(get_genus))

In [8]:
# Load pydamage data
# Step 1: Locate files
file_list = find_pydamage_files(BASE_DIR, RESULT_FILENAME)

# Step 2: Load and annotate
dataframes = [load_and_annotate(info) for info in file_list]

# Step 3: Concatenate into single DataFrame
pydamage_df = pd.concat(dataframes, ignore_index=True)

# Step 4: Standardize assembly names
pydamage_df['sample'] = pydamage_df['sample'].apply(standardize_assembly_name)

### Quality control

In [9]:
pydamage_df.head()
pydamage_df['sample'].unique()

array(['EXB080_A0101', 'TDM033', 'TDM042', 'EXB080_A0901', 'EXB080_A0801',
       'TDM056', 'TDM030', 'TDM001', 'TDM038', 'TDM051', 'TDM017',
       'TDM019', 'TDM055', 'TDM036', 'TDM003', 'TDM037', 'TDM027',
       'EXB080_A1101', 'TDM013', 'TDM053', 'TDM052', 'TDM060', 'TDM049',
       'TDM005', 'TDM043', 'TDM014', 'TDM023', 'TDM015', 'TDM054',
       'TDM024', 'EXB080_A1001', 'TDM007', 'TDM034', 'TDM016', 'TDM008',
       'TDM012', 'EXB080_A1201', 'TDM022', 'TDM035', 'TDM006', 'TDM057',
       'TDM010', 'TDM045', 'TDM028', 'TDM025', 'TDM046', 'TDM020',
       'TDM061', 'EXB080_A0102', 'TDM011', 'TDM039', 'TDM031', 'TDM002',
       'TDM029', 'TDM004', 'TDM021', 'EXB080_A1401', 'EXB080_A1301',
       'TDM040', 'TDM044', 'TDM048', 'TDM018', 'TDM026', 'TDM041',
       'TDM032', 'TDM059', 'TDM047', 'TDM050', 'TDM058'], dtype=object)

In [10]:

tax_df['sample'].unique()

array(['TDM056', 'TDM025', 'TDM053', 'TDM061', 'TDM051', 'TDM019',
       'EXB080_A1101', 'TDM029', 'EXB080_A0801', 'TDM010', 'TDM016',
       'TDM054', 'TDM001', 'TDM038', 'TDM052', 'TDM020', 'TDM013',
       'TDM055', 'TDM044', 'EXB080_A1001', 'TDM050', 'TDM031', 'TDM039',
       'EXB080_A0901', 'TDM046', 'EXB080_A0101', 'TDM006', 'TDM060',
       'TDM002', 'TDM030', 'TDM035', 'TDM058', 'EXB080_A1201', 'TDM015',
       'TDM005', 'TDM018', 'TDM017', 'TDM059', 'TDM003', 'TDM012',
       'TDM008', 'EXB080_A1401', 'TDM022', 'TDM028', 'TDM027', 'TDM026',
       'TDM049', 'TDM045', 'TDM048', 'TDM036', 'TDM021', 'TDM037',
       'TDM033', 'TDM047', 'EXB080_A1301', 'EXB080_A0102', 'TDM023',
       'TDM024', 'TDM004', 'TDM043', 'TDM011', 'TDM041', 'TDM032',
       'TDM014', 'TDM042', 'TDM057', 'TDM007', 'TDM034', 'TDM040'],
      dtype=object)

In [11]:
pd.options.display.max_rows = 4000
contignr=pydamage_df.groupby(['sample'])['contig'].count()
print(contignr)

sample
EXB080_A0101       500
EXB080_A0102       658
EXB080_A0801     13181
EXB080_A0901      7063
EXB080_A1001      4341
EXB080_A1101      6574
EXB080_A1201      6078
EXB080_A1301     10032
EXB080_A1401      3975
TDM001          101739
TDM002           80131
TDM003           65595
TDM004           53669
TDM005           45573
TDM006           31067
TDM007           26105
TDM008           32102
TDM010           69972
TDM011           48712
TDM012           17425
TDM013           54751
TDM014           57608
TDM015           42869
TDM016           48549
TDM017           55289
TDM018           49128
TDM019           50802
TDM020           34657
TDM021           60583
TDM022           28772
TDM023           46897
TDM024           51687
TDM025           24599
TDM026           24853
TDM027           48475
TDM028           35208
TDM029           49519
TDM030           41507
TDM031           66849
TDM032           33565
TDM033           41468
TDM034           53078
TDM035           51742
TDM036           26154
TDM037           39339
TDM038           38298
TDM039           23459
TDM040           22696
TDM041           19331
TDM042           24153
TDM043            2284
TDM044            5098
TDM045           31352
TDM046           31210
TDM047           21550
TDM048           25638
TDM049           24576
TDM050           21172
TDM051           28389
TDM052           29185
TDM053           24806
TDM054           22650
TDM055           19903
TDM056           27574
TDM057           19352
TDM058           31611
TDM059           21098
TDM060           12533
TDM061           32445
Name: contig, dtype: int64

In [12]:
pd.options.display.max_rows = 4000
assemblylength=pydamage_df.groupby(['sample'])['reflen'].sum()
print(assemblylength)

sample
EXB080_A0101       126525
EXB080_A0102       170283
EXB080_A0801      5019349
EXB080_A0901      2530167
EXB080_A1001      1747513
EXB080_A1101      2341815
EXB080_A1201      2769890
EXB080_A1301      3682717
EXB080_A1401      2028478
TDM001          106107486
TDM002           84817480
TDM003           81330653
TDM004           57818381
TDM005           56296858
TDM006           39358294
TDM007           40088542
TDM008           36833252
TDM010           69340663
TDM011           51012858
TDM012           20165542
TDM013           51594039
TDM014           58499409
TDM015           37718055
TDM016           49864394
TDM017           48044553
TDM018           45547982
TDM019           56820283
TDM020           37017429
TDM021           61538095
TDM022           28061196
TDM023           38223225
TDM024           38034926
TDM025           22934633
TDM026           20460615
TDM027           34648094
TDM028           28792812
TDM029           39109896
TDM030           37676907
TDM031           55324350
TDM032           44804402
TDM033           43714244
TDM034           40170286
TDM035           38335963
TDM036           24614868
TDM037           34180250
TDM038           32313978
TDM039           17563256
TDM040           19211484
TDM041           18227614
TDM042           20639069
TDM043             751355
TDM044            2068432
TDM045           22218832
TDM046           25004762
TDM047           16183122
TDM048           22629738
TDM049           22699330
TDM050           22219583
TDM051           17401075
TDM052           20602005
TDM053           23206127
TDM054           23207945
TDM055           14792300
TDM056           27819860
TDM057           22299424
TDM058           34651810
TDM059           19585455
TDM060           20168402
TDM061           25807370
Name: reflen, dtype: int64

In [13]:
print("contigs in pydamage output:", len(pydamage_df), "\ncontigs in tax. annotation: ", len(tax_df))

contigs in pydamage output: 2302803
contigs in tax. annotation:  2073597

Not all contigs were taxonomically annotated.

### Merge data

In [14]:
full_df = pydamage_df.merge(tax_df, on=["sample", "contig"] , how="left")
len(full_df)

2302803

### Calculating coverages in TPM
I'm aiming to use this to quantify, which genera are more abundant in Extraction blanks EXB than in stalagmite samples (TDM)

In [15]:
 # Step 1: Calculate RPK for each contig
full_df["rpk"] = full_df["nb_reads_aligned"] / (full_df["reflen"] / 1000)

# Step 2: Calculate TPM per sample
# Group by sample, calculate per-sample sum of RPKs
full_df["rpk_sum"] = full_df.groupby("sample")["rpk"].transform("sum")

# Step 3: Compute TPM
full_df["tpm"] = (full_df["rpk"] / full_df["rpk_sum"]) * 1e6

In [16]:
full_df.groupby(['sample'])['tpm'].sum()

sample
EXB080_A0101    1000000.0
EXB080_A0102    1000000.0
EXB080_A0801    1000000.0
EXB080_A0901    1000000.0
EXB080_A1001    1000000.0
EXB080_A1101    1000000.0
EXB080_A1201    1000000.0
EXB080_A1301    1000000.0
EXB080_A1401    1000000.0
TDM001          1000000.0
TDM002          1000000.0
TDM003          1000000.0
TDM004          1000000.0
TDM005          1000000.0
TDM006          1000000.0
TDM007          1000000.0
TDM008          1000000.0
TDM010          1000000.0
TDM011          1000000.0
TDM012          1000000.0
TDM013          1000000.0
TDM014          1000000.0
TDM015          1000000.0
TDM016          1000000.0
TDM017          1000000.0
TDM018          1000000.0
TDM019          1000000.0
TDM020          1000000.0
TDM021          1000000.0
TDM022          1000000.0
TDM023          1000000.0
TDM024          1000000.0
TDM025          1000000.0
TDM026          1000000.0
TDM027          1000000.0
TDM028          1000000.0
TDM029          1000000.0
TDM030          1000000.0
TDM031          1000000.0
TDM032          1000000.0
TDM033          1000000.0
TDM034          1000000.0
TDM035          1000000.0
TDM036          1000000.0
TDM037          1000000.0
TDM038          1000000.0
TDM039          1000000.0
TDM040          1000000.0
TDM041          1000000.0
TDM042          1000000.0
TDM043          1000000.0
TDM044          1000000.0
TDM045          1000000.0
TDM046          1000000.0
TDM047          1000000.0
TDM048          1000000.0
TDM049          1000000.0
TDM050          1000000.0
TDM051          1000000.0
TDM052          1000000.0
TDM053          1000000.0
TDM054          1000000.0
TDM055          1000000.0
TDM056          1000000.0
TDM057          1000000.0
TDM058          1000000.0
TDM059          1000000.0
TDM060          1000000.0
TDM061          1000000.0
Name: tpm, dtype: float64

### Identify genera that are robustly more abundant in TDM samples compared to EXB

Selection was done based on TPM coverage values. TPM values of contigs assigned to the same genus were summed up (cumulative TPM). I then filtered for genera, that hat a higher cumulative TPM in >95% of the samples compared to the maximum cumulative TPM in the extraction blanks.

In [17]:
counts = (
    full_df.groupby(['sample', 'genus'])['tpm']
      .sum()
      .reset_index(name='cumulative_tpm')
)

In [18]:
counts['sample_type'] = counts['sample'].apply(lambda s: 'EXB' if s.startswith('EXB') else 'TDM')
counts

             sample              genus  cumulative_tpm sample_type
0      EXB080_A0101       Burkholderia   323807.154961         EXB
1      EXB080_A0101  Carltongylesvirus      529.368277         EXB
2      EXB080_A0101              Culex     4958.320414         EXB
3      EXB080_A0101             Elysia     3942.647391         EXB
4      EXB080_A0101        Escherichia     3870.270289         EXB
...             ...                ...             ...         ...
26562        TDM061  Vulcaniibacterium       53.988513         TDM
26563        TDM061        Xanthomonas       64.299224         TDM
26564        TDM061         Xenopsylla       36.527844         TDM
26565        TDM061         Zavarzinia       37.583439         TDM
26566        TDM061           Zoogloea       10.937902         TDM

[26567 rows x 4 columns]

In [19]:
'Select genera, that (cumulatively) have more mapped reads than the maximum number of cumulative mapped reads in EXB samples in 95% of the TDM samples'
robust_genera = []

for genus, group in counts.groupby('genus'):
    exb_vals = group[group['sample_type'] == 'EXB']['cumulative_tpm']
    tdm_vals = group[group['sample_type'] == 'TDM']['cumulative_tpm']
    
    # Always keep if genus is missing in EXB
    if len(exb_vals) == 0:
        robust_genera.append(genus)
        continue

    # Apply >95% rule
    exb_max = exb_vals.max()
    tdm_above_exb = (tdm_vals > exb_max).sum()
    tdm_fraction = tdm_above_exb / 60 

    if tdm_fraction > 0.95:
        robust_genera.append(genus)
robust_genera

['Abditibacterium',
 'Abyssibacter',
 'Acanthopleuribacter',
 'Acaryochloris',
 'Acer',
 'Acerihabitans',
 'Acetobacteroides',
 'Acetomicrobium',
 'Acetonema',
 'Achromatium',
 'Acidaminococcus',
 'Acidibrevibacterium',
 'Acidicapsa',
 'Acidiferrimicrobium',
 'Acidiferrobacter',
 'Acidihalobacter',
 'Acidimicrobium',
 'Acidiphilium',
 'Acidipila',
 'Acidipropionibacterium',
 'Acidisoma',
 'Aciditerrimonas',
 'Acidithiobacillus',
 'Acidithrix',
 'Acidobacterium',
 'Acidocella',
 'Acidothermus',
 'Acorus',
 'Acrobeloides',
 'Acrocarpospora',
 'Acromyrmex',
 'Acropora',
 'Actibacterium',
 'Actimicrobium',
 'Actinacidiphila',
 'Actinoallomurus',
 'Actinobacillus',
 'Actinocatenispora',
 'Actinocorallia',
 'Actinocrinis',
 'Actinokineospora',
 'Actinomadura',
 'Actinomarinicola',
 'Actinomortierella',
 'Actinomyces',
 'Actinophytocola',
 'Actinopolymorpha',
 'Actinopolyspora',
 'Actinospica',
 'Actinosynnema',
 'Actinotalea',
 'Actomonas',
 'Acutalibacter',
 'Acuticoccus',
 'Adhaeribacter',
 'Adineta',
 'Adonisia',
 'Aeoliella',
 'Aeribacillus',
 'Aerobium',
 'Aerococcus',
 'Aeromicrobium',
 'Aeropyrum',
 'Aerosticca',
 'Aestuariicoccus',
 'Aestuariimicrobium',
 'Aestuariispira',
 'Aestuariivirga',
 'Aetherobacter',
 'Aetokthonos',
 'Afifella',
 'Agaribacillus',
 'Agaricicola',
 'Agarilytica',
 'Agarivorans',
 'Aggregatilinea',
 'Aggregicoccus',
 'Agilicoccus',
 'Agreia',
 'Agrilutibacter',
 'Agrococcus',
 'Agromyces',
 'Ahniella',
 'Ahrensia',
 'Akanthomyces',
 'Akkermansia',
 'Albidovulum',
 'Albimonas',
 'Alcanivorax',
 'Aldersonia',
 'Alexandrium',
 'Algicola',
 'Algihabitans',
 'Algimonas',
 'Algiphilus',
 'Aliamphritea',
 'Aliarcobacter',
 'Alicyclobacillus',
 'Alienimonas',
 'Aliidiomarina',
 'Aliidongia',
 'Aliiglaciecola',
 'Aliiroseovarius',
 'Aliitabrizicola',
 'Alishewanella',
 'Aliterella',
 'Alkalicoccus',
 'Alkalihalobacillus',
 'Alkalihalobacterium',
 'Alkalilimnicola',
 'Alkalimarinus',
 'Alkalimonas',
 'Alkalinema',
 'Alkalisalibacterium',
 'Alkalispirillum',
 'Alkalispirochaeta',
 'Allacma',
 'Alloacidobacterium',
 'Alloalcanivorax',
 'Allobaculum',
 'Allobranchiibius',
 'Allochromatium',
 'Allocoleopsis',
 'Allofrancisella',
 'Allohahella',
 'Allokutzneria',
 'Allomeiothermus',
 'Allomesorhizobium',
 'Allomuricauda',
 'Allonocardiopsis',
 'Allopseudospirillum',
 'Allopusillimonas',
 'Allorhizocola',
 'Allosphingosinicella',
 'Alsobacter',
 'Alteraquisediminimonas',
 'Altererythrobacter',
 'Alterirhizorhabdus',
 'Alteromonas',
 'Amantichitinum',
 'Amaricoccus',
 'Amazonocrinis',
 'Amblyomma',
 'Aminobacter',
 'Ammonifex',
 'Ammoniphilus',
 'Amnibacterium',
 'Amorphus',
 'Amphibalanus',
 'Amphimedon',
 'Amphiplicatus',
 'Amphritea',
 'Amycolatopsis',
 'Amyelois',
 'Amygdalobacter',
 'Anabaena',
 'Anaerobaca',
 'Anaerobacillus',
 'Anaerobacterium',
 'Anaerobranca',
 'Anaerohalosphaera',
 'Anaerolinea',
 'Anaeromyxobacter',
 'Anaerosalibacter',
 'Anaerospora',
 'Anaerostipes',
 'Anaerotalea',
 'Anaerotruncus',
 'Anaerovibrio',
 'Anas',
 'Anatilimnocola',
 'Ancylobacter',
 'Ancylothrix',
 'Anderseniella',
 'Anditalea',
 'Andreprevotia',
 'Aneurinibacillus',
 'Anguilla',
 'Angustibacter',
 'Anianabacter',
 'Anisakis',
 'Anophryoides',
 'Anoxybacillus',
 'Anoxybacteroides',
 'Anthocerotibacter',
 'Antichaacvirus',
 'Antribacter',
 'Antricoccus',
 'Antrihabitans',
 'Aphanomyces',
 'Aphanothece',
 'Aphis',
 'Aporhodopirellula',
 'Aquabacter',
 'Aquamicrobium',
 'Aquariibacter',
 'Aquaspirillum',
 'Aquibaculum',
 'Aquibium',
 'Aquicella',
 'Aquidulcibacter',
 'Aquihabitans',
 'Aquimarina',
 'Aquimonas',
 'Aquincola',
 'Aquipseudomonas',
 'Aquipuribacter',
 'Aquisalimonas',
 'Aquisediminimonas',
 'Aquisphaera',
 'Aquitalea',
 'Arabidopsis',
 'Arachidicoccus',
 'Arcanobacterium',
 'Arcella',
 'Arcicella',
 'Arcobacter',
 'Arctia',
 'Ardenticatena',
 'Arenibaculum',
 'Arenicella',
 'Arenimonas',
 'Argonema',
 'Arhodomonas',
 'Aricia',
 'Arion',
 'Armatimonas',
 'Aromia',
 'Arsenicibacter',
 'Arsenicicoccus',
 'Arsukibacterium',
 'Artemia',
 'Arundo',
 'Asanoa',
 'Ascidiaceihabitans',
 'Asticcacaulis',
 'Astrephomene',
 'Atlantibacter',
 'Atlanticothrix',
 'Atopobacter',
 'Atopomonas',
 'Atribacter',
 'Aurantiacibacter',
 'Aurantibacillus',
 'Aurantimonas',
 'Aureimonas',
 'Aureisphaera',
 'Aureivirga',
 'Austwickia',
 'Auxenochlorella',
 'Axeltriavirus',
 'Azoarcus',
 'Azohydromonas',
 'Azomonas',
 'Azonexus',
 'Azorhizobium',
 'Azospira',
 'Azotobacter',
 'Azotosporobacter',
 'Azovibrio',
 'Babesia',
 'Bacterioplanes',
 'Bacteriovorax',
 'Bactrocera',
 'Baekduia',
 'Bailinhaonella',
 'Balaenoptera',
 'Balneatrix',
 'Bambusicola',
 'Banduia',
 'Bartonella',
 'Basidiobolus',
 'Bauldia',
 'Beggiatoa',
 'Beijerinckia',
 'Bellilinea',
 'Bernardetia',
 'Bhargavaea',
 'Billgrantia',
 'Bilophila',
 'Biomphalaria',
 'Bismarckvirus',
 'Blastochloris',
 'Blastococcus',
 'Blastomonas',
 'Blastomyces',
 'Blastopirellula',
 'Blattabacterium',
 'Blattella',
 'Blautia',
 'Blepharisma',
 'Bolinopsis',
 'Bombus',
 'Bombyx',
 'Bos',
 'Botrimarina',
 'Bowmanella',
 'Brachionus',
 'Brachybacterium',
 'Brachymonas',
 'Brachyspira',
 'Brasilonema',
 'Brassica',
 'Bremerella',
 'Breoghania',
 'Brevibacterium',
 'Brevifollis',
 'Breznakibacter',
 'Brochothrix',
 'Brucella',
 'Bryobacter',
 'Byssothecium',
 'Bythopirellula',
 'Caenimonas',
 'Caenispirillum',
 'Caenorhabditis',
 'Cajanus',
 'Caldalkalibacillus',
 'Caldanaerobacter',
 'Calderihabitans',
 'Caldichromatium',
 'Caldicoprobacter',
 'Caldimicrobium',
 'Caldinitratiruptor',
 'Caldisalinibacter',
 'Calditerricola',
 'Caldithrix',
 'Caldora',
 'Caldovatus',
 'Calidifontibacillus',
 'Calidithermus',
 'Callosobruchus',
 'Calorimonas',
 'Calothrix',
 'Calycomorphotria',
 'Camelimonas',
 'Camellia',
 'Camponotus',
 'Canavalia',
 'Candida',
 'Candidatus Abzuiibacterium',
 'Candidatus Acetithermum',
 'Candidatus Acidiferrum',
 'Candidatus Aciduliprofundum',
 'Candidatus Acidulodesulfobacterium',
 'Candidatus Aegiribacteria',
 'Candidatus Aeolococcus',
 'Candidatus Alcium',
 'Candidatus Anammoximicrobium',
 'Candidatus Angelobacter',
 'Candidatus Anoxymicrobium',
 'Candidatus Aquicultor',
 'Candidatus Argoarchaeum',
 'Candidatus Auribacter',
 'Candidatus Avichristensenella',
 'Candidatus Babela',
 'Candidatus Bathycorpusculum',
 'Candidatus Bealeia',
 'Candidatus Berkiella',
 'Candidatus Binatus',
 'Candidatus Bipolaricaulis',
 'Candidatus Bodocaedibacter',
 'Candidatus Borrarchaeum',
 'Candidatus Brocadia',
 'Candidatus Caldarchaeum',
 'Candidatus Cardinium',
 'Candidatus Cenarchaeum',
 'Candidatus Chaera',
 'Candidatus Chloroploca',
 'Candidatus Cloacimonas',
 'Candidatus Competibacter',
 'Candidatus Contendibacter',
 'Candidatus Criblamydia',
 'Candidatus Cryosericum',
 'Candidatus Cyanaurora',
 'Candidatus Danuiimicrobium',
 'Candidatus Deferrimicrobium',
 'Candidatus Desulfatibia',
 'Candidatus Desulfatifera',
 'Candidatus Desulfobacillus',
 'Candidatus Desulfobia',
 'Candidatus Desulfofervidus',
 'Candidatus Desulfolinea',
 'Candidatus Desulforudis',
 'Candidatus Didemnitutus',
 'Candidatus Electrothrix',
 'Candidatus Endobugula',
 'Candidatus Endonucleibacter',
 'Candidatus Entotheonella',
 'Candidatus Eremiobacter',
 'Candidatus Fervidibacter',
 'Candidatus Fimadaptatus',
 'Candidatus Finniella',
 'Candidatus Formimonas',
 'Candidatus Galligastranaerophilus',
 'Candidatus Ghiorseimicrobium',
 'Candidatus Gullanella',
 'Candidatus Hadarchaeum',
 'Candidatus Hakubella',
 'Candidatus Halobonum',
 'Candidatus Hecatella',
 'Candidatus Hydrogenedens',
 'Candidatus Hydrogenisulfobacillus',
 'Candidatus Iainarchaeum',
 'Candidatus Infernicultor',
 'Candidatus Jettenia',
 'Candidatus Kapaibacterium',
 'Candidatus Kentrum',
 'Candidatus Korobacter',
 'Candidatus Kryptobacter',
 'Candidatus Kuenenia',
 'Candidatus Kutchimonas',
 'Candidatus Laterigemmans',
 'Candidatus Litorirhabdus',
 'Candidatus Magnetaquicoccus',
 'Candidatus Magnetobacterium',
 'Candidatus Magnetoglobus',
 'Candidatus Magnetominusculus',
 'Candidatus Magnetomorum',
 'Candidatus Manganitrophus',
 'Candidatus Marithrix',
 'Candidatus Methanofastidiosum',
 'Candidatus Methanogaster',
 'Candidatus Methanoliparum',
 'Candidatus Methanomethylicus',
 'Candidatus Methanoperedens',
 'Candidatus Methanophaga',
 'Candidatus Methylacidithermus',
 'Candidatus Methylomirabilis',
 'Candidatus Methylophosphatis',
 'Candidatus Methylospira',
 'Candidatus Methylumidiphilus',
 'Candidatus Micrarchaeum',
 'Candidatus Microsaccharimonas',
 'Candidatus Moduliflexus',
 'Candidatus Muiribacterium',
 'Candidatus Nanosalina',
 'Candidatus Nanosynbacter',
 'Candidatus Neptunichlamydia',
 'Candidatus Nitricoxidivorans',
 'Candidatus Nitrobium',
 'Candidatus Nitronauta',
 'Candidatus Nitronereus',
 'Candidatus Nitrosacidococcus',
 'Candidatus Nitrosocaldus',
 'Candidatus Nitrosocosmicus',
 'Candidatus Nitrosopelagicus',
 'Candidatus Nitrosotenuis',
 'Candidatus Odyssella',
 'Candidatus Oleimmundimicrobium',
 'Candidatus Omnitrophus',
 'Candidatus Opimibacter',
 'Candidatus Ordinivivax',
 'Candidatus Paceibacter',
 'Candidatus Palauibacter',
 'Candidatus Parabeggiatoa',
 'Candidatus Pelagibacter',
 'Candidatus Peribacter',
 'Candidatus Phaeomarinibacter',
 'Candidatus Phytoplasma',
 'Candidatus Polarisedimenticola',
 'Candidatus Poriferisodalis',
 'Candidatus Promineifilum',
 'Candidatus Protochlamydia',
 'Candidatus Psychracetigena',
 'Candidatus Raskinella',
 'Candidatus Reconcilbacillus',
 'Candidatus Rhabdochlamydia',
 'Candidatus Roseilinea',
 'Candidatus Saccharicenans',
 'Candidatus Saccharimonas',
 'Candidatus Scalindua',
 'Candidatus Segetimicrobium',
 'Candidatus Soleaferrea',
 'Candidatus Solibacter',
 'Candidatus Solincola',
 'Candidatus Sulfobium',
 'Candidatus Sulfomarinibacter',
 'Candidatus Sulfopaludibacter',
 'Candidatus Sulfotelmatobacter',
 'Candidatus Sulfuritelmatomonas',
 'Candidatus Symbiobacter',
 'Candidatus Synchoanobacter',
 'Candidatus Syntropharchaeum',
 'Candidatus Taenaricola',
 'Candidatus Tenderia',
 'Candidatus Termititenax',
 'Candidatus Terraquivivens',
 'Candidatus Thiocaldithrix',
 'Candidatus Thiodiazotropha',
 'Candidatus Thioglobus',
 'Candidatus Thiosymbion',
 'Candidatus Trichorickettsia',
 'Candidatus Uabimicrobium',
 'Candidatus Udaeobacter',
 'Candidatus Vecturithrix',
 'Candidatus Viadribacter',
 'Candidatus Viridilinea',
 'Candidatus Vondammii',
 'Candidozyma',
 'Capillibacterium',
 'Capillimicrobium',
 'Capsulimonas',
 'Carbonactinospora',
 'Carboxydocella',
 'Carboxydothermus',
 'Cardiobacterium',
 'Carpinus',
 'Casimicrobium',
 'Castellaniella',
 'Catalinimonas',
 'Catellatospora',
 'Catelliglobosispora',
 'Catenuloplanes',
 'Caulifigura',
 'Cedecea',
 'Celeribacter',
 'Cellulomonas',
 'Centrocercus',
 'Centruroides',
 'Cerasicoccus',
 'Ceratobasidium',
 'Ceratopteris',
 'Cesiribacter',
 'Chakrabartyvirus',
 'Chamaesiphon',
 'Chania',
 'Chelativorans',
 'Chelatococcus',
 'Chengkuizengella',
 'Chiayiivirga',
 'Chidieberevirus',
 'Chionoecetes',
 'Chitinibacter',
 'Chitinilyticum',
 'Chitinimonas',
 'Chitiniphilus',
 'Chitinolyticbacter',
 'Chlamydia',
 'Chlamydiifrater',
 'Chlamydomonas',
 'Chloebia',
 'Chlorobaculum',
 'Chlorobium',
 'Chloroflexus',
 'Chlorogloeopsis',
 'Chloroherpeton',
 'Chloropicon',
 'Chlorovirus',
 'Chondromyces',
 'Chondrus',
 'Christiangramia',
 'Chromatium',
 'Chromatocurvus',
 'Chromohalobacter',
 'Chroococcidiopsis',
 'Chryseolinea',
 'Chryseosolibacter',
 'Chryseotalea',
 'Chrysiogenes',
 'Chthoniobacter',
 'Chthonobacter',
 'Chthonomonas',
 'Ciceribacter',
 'Citricoccus',
 'Citrifermentans',
 'Citromicrobium',
 'Cladocopium',
 'Cladophialophora',
 'Clarias',
 'Cloacibacillus',
 'Clonorchis',
 'Clonostachys',
 'Cobetia',
 'Coccidioides',
 'Cocleimonas',
 'Cognatiluteimonas',
 'Cognatilysobacter',
 'Cognatishimia',
 'Cognatiyoonia',
 'Cohaesibacter',
 'Cohnella',
 'Colias',
 'Colletotrichum',
 'Collibacillus',
 'Collimonas',
 'Collinsella',
 'Columba',
 'Colwellia',
 'Conexibacter',
 'Conexivisphaera',
 'Congregibacter',
 'Contarinia',
 'Coptotermes',
 'Coraliomargarita',
 'Corallincola',
 'Corallococcus',
 'Coralloluteibacterium',
 'Cordyceps',
 'Corethrella',
 'Corynebacterium',
 'Couchioplanes',
 'Crateriforma',
 'Crenalkalicoccus',
 'Crenobacter',
 'Crenothrix',
 'Croceibacter',
 'Croceibacterium',
 'Croceicoccus',
 'Crocosphaera',
 'Cronobacter',
 'Crossiella',
 'Cryobacterium',
 'Cryptosporangium',
 'Cryptotermes',
 'Cucumibacter',
 'Cucumis',
 'Cuerna',
 'Culicoides',
 'Culicoidibacter',
 'Cuniculiplasma',
 'Curtobacterium',
 'Cuspidothrix',
 'Cutibacterium',
 'Cyanobium',
 'Cyanomargarita',
 'Cyanothece',
 'Cyclobacterium',
 'Cycloclasticus',
 'Cyclonatronum',
 'Cydia',
 'Cylicostephanus',
 'Cylindrospermopsis',
 'Cylindrospermum',
 'Cyphomyrmex',
 'Cypionkella',
 'Cyprideis',
 'Cystobacter',
 'Cystobasidium',
 'Cytophaga',
 'Cytospora',
 'Dactylosporangium',
 'Daejeonella',
 'Dankookia',
 'Dasania',
 'Dawidia',
 'Dechloromonas',
 'Deferrisoma',
 'Defluviicoccus',
 'Defluviitalea',
 'Dehalobacter',
 'Dehalococcoides',
 'Dehalogenimonas',
 'Deinobacterium',
 'Deinococcus',
 'Demequina',
 'Dendroctonus',
 'Denitratimonas',
 'Denitratisoma',
 'Denitromonas',
 'Denitrovibrio',
 'Dermatobacter',
 'Dermatophagoides',
 'Derxia',
 'Deseoctovirus',
 'Desertibacillus',
 'Desertibaculum',
 'Desertimonas',
 'Desmonostoc',
 'Desmospora',
 'Desulfallas',
 'Desulfamplus',
 'Desulfarculus',
 'Desulfatibacillum',
 'Desulfatiglans',
 'Desulfatirhabdium',
 'Desulfatitalea',
 'Desulfitobacterium',
 'Desulfobacca',
 'Desulfobacter',
 'Desulfobacterium',
 'Desulfobacula',
 'Desulfobaculum',
 'Desulfobotulus',
 'Desulfobulbus',
 'Desulfocapsa',
 'Desulfococcus',
 'Desulfocucumis',
 'Desulfofarcimen',
 'Desulfoferrobacter',
 'Desulfoferula',
 'Desulfofundulus',
 'Desulfofustis',
 'Desulfoglaeba',
 'Desulfogranum',
 'Desulfolithobacter',
 'Desulfoluna',
 'Desulfolutivibrio',
 'Desulfomonile',
 'Desulfonatronum',
 'Desulfonauticus',
 'Desulfonema',
 'Desulfopila',
 'Desulfoplanes',
 'Desulforadius',
 'Desulforamulus',
 'Desulforhabdus',
 'Desulfosalsimonas',
 'Desulfosarcina',
 'Desulfosediminicola',
 'Desulfospira',
 'Desulfosporosinus',
 'Desulfotignum',
 'Desulfotomaculum',
 'Desulfotruncus',
 'Desulfovermiculus',
 'Desulfovibrio',
 'Desulfovirgula',
 'Desulfuribacillus',
 'Desulfurispirillum',
 'Desulfurivibrio',
 'Desulfurococcus',
 'Desulfuromonas',
 'Desulfuromusa',
 'Dethiobacter',
 'Dethiosulfatarculus',
 'Diacronema',
 'Dialister',
 'Diaminobutyricimonas',
 'Diaphorobacter',
 'Diatraea',
 'Dichotomicrobium',
 'Dickeya',
 'Dictyobacter',
 'Dictyoglomus',
 'Didymodactylos',
 'Dietzia',
 'Dillenia',
 'Diorhabda',
 'Diploptera',
 'Dipteronia',
 'Dissulfurirhabdus',
 'Dissulfurispira',
 'Ditylenchus',
 'Diversispora',
 'Docaquintavirus',
 'Dongia',
 'Dongshaea',
 'Dorcoceras',
 'Draconibacterium',
 'Drechslerella',
 'Drosophila',
 'Drouetiella',
 'Dysgonomonas',
 'Dysosmobacter',
 'Ectobacillus',
 'Ectopseudomonas',
 'Ectothiorhodosinus',
 'Ectothiorhodospira',
 'Edaphobacter',
 'Edaphocola',
 'Edaphosphingomonas',
 'Edwardsiella',
 'Effusibacillus',
 'Eggerthella',
 'Egibacter',
 'Egicoccus',
 'Eikenella',
 'Eilatimonas',
 'Eisenibacter',
 'Ekhidna',
 'Elaphomyces',
 'Eleftheria',
 'Elioraea',
 'Elongatibacter',
 'Elstera',
 'Elusimicrobium',
 'Embleya',
 'Emcibacter',
 'Endobacter',
 'Engelhardtia',
 'Enhydrobacter',
 'Enhygromyxa',
 'Enorma',
 'Ensifer',
 'Enterocloster',
 'Enterovirga',
 'Entomortierella',
 'Eoetvoesiella',
 'Ephemeroptericola',
 'Epibacterium',
 'Epicauta',
 'Epilithonimonas',
 'Equus',
 'Eragrostis',
 'Ereboglobus',
 'Erwinia',
 'Erysiphe',
 'Escallonia',
 'Estrella',
 'Eubacterium',
 'Eudoraea',
 'Eumeta',
 'Euphydryas',
 'Eutreptiella',
 'Euzebya',
 'Evansella',
 'Exiguobacterium',
 'Exilibacterium',
 'Faecalibacterium',
 'Faecalicoccus',
 'Falco',
 'Falsihalocynthiibacter',
 'Falsirhodobacter',
 'Falsiroseomonas',
 'Faucicola',
 'Ferirhizobium',
 'Ferribacterium',
 'Ferrigenium',
 'Ferrimicrobium',
 'Ferrimonas',
 'Ferriphaselus',
 'Ferrithrix',
 'Ferroacidibacillus',
 'Ferrovum',
 'Ferruginivarius',
 'Fervidicola',
 'Fibrella',
 'Fibrobacter',
 'Fictibacillus',
 'Filomicrobium',
 'Fimbriiglobus',
 'Fimbriimonas',
 'Fimicolochytrium',
 'Finegoldia',
 'Fischerella',
 'Flammeovirga',
 'Flaumdravirus',
 'Flavilitoribacter',
 'Flavimaribacter',
 'Flavimobilis',
 'Flavisolibacter',
 'Flavisphingomonas',
 'Flavonifractor',
 'Flectobacillus',
 'Flexibacter',
 'Flexistipes',
 'Flexivirga',
 'Floridanema',
 'Fluoribacter',
 'Fluviibacter',
 'Fluviicoccus',
 'Fluviicola',
 'Fodinibacter (ex Wang et al. 2009)',
 'Fodinibius',
 'Fodinicola',
 'Fodinicurvata',
 'Fodinisporobacter',
 'Folsomia',
 'Fontimonas',
 'Fontisphaera',
 'Formivibrio',
 'Formosimonas',
 'Fortiea',
 'Frankia',
 'Frankliniella',
 'Frateuria',
 'Fredinandcohnia',
 'Friedmanniella',
 'Frigidibacter',
 'Frigoriglobus',
 'Fuerstiella',
 'Fulvimarina',
 'Fulvimonas',
 'Fulvitalea',
 'Fulvivirga',
 'Fundidesulfovibrio',
 'Fundulus',
 'Funneliformis',
 'Futiania',
 'Gaetbulibacter',
 'Gaeumannomyces',
 'Gaiella',
 'Gajwadongvirus',
 'Gallaecimonas',
 'Galleria',
 'Gallionella',
 'Gallus',
 'Gambusia',
 'Gandjariella',
 'Geitlerinema',
 'Gelidibacter',
 'Geminicoccus',
 'Geminocystis',
 'Gemmata',
 'Gemmatirosa',
 'Gemmiger',
 'Genlisea',
 'Geoalkalibacter',
 'Geoanaerobacter',
 'Geobacter',
 'Geodermatophilus',
 'Geodia',
 'Geoglobus',
 'Geomesophilobacter',
 'Geomonas',
 'Geopsychrobacter',
 'Georgenia',
 'Georgfuchsia',
 'Geotalea',
 'Geothermobacter',
 'Geothrix',
 'Ghiorsea',
 'Gillisia',
 'Gilvimarinus',
 'Glacieibacterium',
 'Glaciimonas',
 'Globisporangium',
 'Gloeobacter',
 'Gloeocapsa',
 'Gloeocapsopsis',
 'Gloeomargarita',
 'Gloeothece',
 'Gluconacetobacter',
 'Gluconobacter',
 'Glutamicibacter',
 'Glutinoglossum',
 'Glycine',
 'Glycocaulis',
 'Glycomyces',
 'Gomphillus',
 'Gomphosphaeria',
 'Gordonibacter',
 'Gorillibacterium',
 'Gossypium',
 'Gottfriedia',
 'Gottschalkia',
 'Govanella',
 'Gracilibacillus',
 'Gracilibacter',
 'Gracilimonas',
 'Grallaria',
 'Granulibacter',
 'Granulicella',
 'Granulosicoccus',
 'Grimontia',
 'Gryllotalpicola',
 'Gryllus',
 'Gulbenkiania',
 'Gulosibacter',
 'Guptibacillus',
 'Guyparkeria',
 'Haemonchus',
 'Hafnia',
 'Hahella',
 'Halalkalibaculum',
 'Halanaerobium',
 'Halarcobacter',
 'Halarsenatibacter',
 'Haliangium',
 'Haliea',
 'Halioglobus',
 'Halioxenophilus',
 'Haliscomenobacter',
 'Haloactinopolyspora',
 'Haloarchaeobius',
 'Haloarcula',
 'Halobacillus',
 'Halobacteriovorax',
 'Halobacterium',
 'Halobaculum',
 'Halocatena',
 'Halochromatium',
 'Halococcus',
 'Halodesulfurarchaeum',
 'Haloechinothrix',
 'Haloferax',
 'Haloferula',
 'Halofilum',
 'Halogeometricum',
 'Haloglomus',
 'Halomicronema',
 'Halonatronum',
 'Halopelagius',
 'Halopolyspora',
 'Halopseudomonas',
 'Halorhodospira',
 'Halorubrum',
 'Halorussus',
 'Halosolutus',
 'Halostella',
 'Halteria',
 'Handroanthus',
 'Hankyongella',
 'Hansschlegelia',
 'Hapsidospora',
 'Harpegnathos',
 'Hartmannibacter',
 'Hazenella',
 'Heliobacterium',
 ...]

### Exclude contigs from EXB-dominant genera and contigs with <50x coverage

In [20]:
# Step 2: Filter out rows where genus is in that set
filtered_df = full_df[full_df['genus'].isin(robust_genera) &
    (full_df['coverage'] >= 50)]

### Check for continuous presence over time
I selected genera, that - after all filtering steps - appeared >90% of the stalagmite samples

In [21]:
wide_df = (
    filtered_df.groupby(['sample', 'genus'])['contig']
      .count()
      .reset_index(name='n_contigs')  # Step 1: count contigs
      .pivot_table(index='sample', columns='genus', values='n_contigs')  # Step 2: pivot
      .reset_index()  # optional: make 'sample' a column instead of index
)

wide_df = wide_df[~wide_df['sample'].str.startswith('EXB')]
wide_df

genus,sample,Abditibacterium,Abyssibacter,Acanthopleuribacter,Acaryochloris,Acetomicrobium,Achromatium,Acidaminococcus,Acidicapsa,Acidiferrimicrobium,...,Zavarzinia,Zea,Zeimonas,Zemynaea,Zestomonas,Zoogloea,Zooshikella,Zopfia,Zwartia,Zymobacter
2,TDM001,NaN,4.0,NaN,1.0,NaN,NaN,NaN,NaN,2.0,...,NaN,1.0,3.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
3,TDM002,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TDM003,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
5,TDM004,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
6,TDM005,NaN,3.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
7,TDM006,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
8,TDM007,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,TDM008,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
10,TDM010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,1.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
11,TDM011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,TDM012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,TDM013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,TDM014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
15,TDM015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
16,TDM016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
17,TDM017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
18,TDM018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,TDM019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,TDM020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,TDM021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
22,TDM022,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
23,TDM023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,TDM024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
25,TDM025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1.0,NaN
26,TDM026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,TDM027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
28,TDM028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,TDM029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,TDM030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
31,TDM031,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,...,NaN,1.0,1.0,1.0,NaN,4.0,NaN,NaN,NaN,NaN
32,TDM032,NaN,7.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,1.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN
33,TDM033,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
34,TDM034,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN
35,TDM035,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0
36,TDM036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
37,TDM037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,1.0
38,TDM038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
39,TDM039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
40,TDM040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
41,TDM041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
42,TDM042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
43,TDM043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,TDM044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,TDM045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN
46,TDM046,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
47,TDM047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,1.0,NaN
48,TDM048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN
49,TDM049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN
50,TDM050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN
51,TDM051,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN
52,TDM052,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
53,TDM053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN
54,TDM054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,TDM055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,TDM056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,TDM057,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
58,TDM058,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,TDM059,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
60,TDM060,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,TDM061,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Selection of core genera

In [22]:
# Count NaN values in each genus (i.e., each column except 'sample')
na_counts = wide_df.isna().sum()
# Exclude 'sample' column 
na_counts = na_counts.drop('sample', errors='ignore')
# Find genera (column names) with 6 or fewer NaN values
core_genera = na_counts[na_counts < 6].index.tolist()

core_genera

['Candidatus Methylomirabilis',
 'Candidatus Nitrosotenuis',
 'Conexibacter',
 'Nitrosotalea',
 'Nitrospira',
 'Piscinibacter']

### Data frame of core genera contigs

In [23]:
core_df= filtered_df[filtered_df['genus'].isin(core_genera)]

In [24]:
core_df.groupby(['sample','genus'])['contig'].count().unstack(fill_value=0)
#qc.pivot_table(index="sample", columns="genus", values="count", fill_value=0)

genus,Candidatus Methylomirabilis,Candidatus Nitrosotenuis,Conexibacter,Nitrosotalea,Nitrospira,Piscinibacter
sample,,,,,,
EXB080_A0801,0,0,0,0,1,0
EXB080_A0901,0,0,0,0,1,0
TDM001,0,85,3,2,2333,6
TDM002,1,143,8,4,2313,4
TDM003,1,131,19,5,1945,2
TDM004,2,71,7,6,2425,2
TDM005,2,3,33,1,2331,11
TDM006,2,55,43,3,1757,2
TDM007,1,4,31,1,2016,1
TDM008,1,0,1,2,1316,1
TDM010,2,27,10,3,1861,3
TDM011,2,25,32,2,1727,2
TDM012,1,4,6,4,1203,1
TDM013,3,117,31,6,1306,3
TDM014,1,15,28,4,1688,37
TDM015,6,252,82,4,2043,53
TDM016,7,85,126,4,2381,4
TDM017,7,75,103,3,2429,3
TDM018,1,18,56,3,1083,3
TDM019,6,65,128,4,1957,2
TDM020,3,109,12,3,419,3
TDM021,2,90,55,8,832,5
TDM022,12,32,9,2,561,5
TDM023,3,4,45,1,1428,0
TDM024,3,2,68,1,1390,2
TDM025,4,1,10,3,1082,9
TDM026,2,477,8,7,403,2
TDM027,3,415,133,6,963,3
TDM028,7,222,43,7,999,7
TDM029,6,315,99,7,2326,34
TDM030,3,501,40,8,2048,33
TDM031,12,458,192,8,450,70
TDM032,9,74,24,6,439,40
TDM033,1,15,24,4,423,61
TDM034,1,8,162,1,780,8
TDM035,1,3,10,0,1256,4
TDM036,1,4,11,2,1079,5
TDM037,5,3,8,3,1716,3
TDM038,5,498,107,2,2354,4
TDM039,2,506,86,5,2861,2
TDM040,6,191,8,3,3204,3
TDM041,4,88,25,1,3289,4
TDM042,5,744,11,6,2980,1
TDM043,1,0,0,1,335,0
TDM044,0,7,0,1,1326,1
TDM045,3,535,30,9,2620,3
TDM046,13,428,14,3,2968,7
TDM047,10,365,8,3,425,2
TDM048,5,81,7,4,2472,6
TDM049,16,66,9,0,2227,2
TDM050,6,127,9,1,1872,3
TDM051,5,185,5,3,2049,8
TDM052,7,544,5,9,2660,6
TDM053,4,435,13,9,2577,1
TDM054,2,462,122,12,1567,2
TDM055,3,19,41,2,2635,0
TDM056,3,120,3,8,2154,0
TDM057,0,1,0,3,247,1
TDM058,0,8,1,4,42,1
TDM059,0,12,5,4,187,5
TDM060,1,1,2,2,62,3
TDM061,5,0,0,0,28,3

### Extract core genera contigs from assembly fasta files

In [ ]:
'locate assemblies'
assemblies = Path("<path to>/Assemblies").glob("*.contigs.fa.gz")
assemblies_dict = {i.stem.split("-")[2].split(".")[0]:i.as_posix() for i in assemblies}
assemblies_dict

{'TDM032': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM032.contigs.fa.gz',
 'TDM049': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM049.contigs.fa.gz',
 'TDM042': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM042.contigs.fa.gz',
 'TDM061': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM061.contigs.fa.gz',
 'TDM028': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM028.contigs.fa.gz',
 'TDM027': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM027.contigs.fa.gz',
 'TDM031': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM031.contigs.fa.gz',
 'EXB080_A0801': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A0801.contigs.fa.gz',
 'EXB080_A1301': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A1301.contigs.fa.gz',
 'TDM024': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM024.contigs.fa.gz',
 'TDM036': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM036.contigs.fa.gz',
 'TDM043': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM043.contigs.fa.gz',
 'TDM005': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM005.contigs.fa.gz',
 'TDM054': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM054.contigs.fa.gz',
 'TDM021': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM021.contigs.fa.gz',
 'EXB080_A1001': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A1001.contigs.fa.gz',
 'TDM023': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM023.contigs.fa.gz',
 'TDM020': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM020.contigs.fa.gz',
 'TDM003': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM003.contigs.fa.gz',
 'TDM010': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM010.contigs.fa.gz',
 'TDM007': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM007.contigs.fa.gz',
 'TDM057': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM057.contigs.fa.gz',
 'TDM006': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM006.contigs.fa.gz',
 'TDM025': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM025.contigs.fa.gz',
 'TDM012': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM012.contigs.fa.gz',
 'TDM056': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM056.contigs.fa.gz',
 'EXB080_A0102': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A0102.contigs.fa.gz',
 'TDM014': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM014.contigs.fa.gz',
 'TDM035': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM035.contigs.fa.gz',
 'TDM039': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM039.contigs.fa.gz',
 'TDM016': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM016.contigs.fa.gz',
 'EXB080_A0101': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A0101.contigs.fa.gz',
 'EXB080_A1101': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A1101.contigs.fa.gz',
 'TDM038': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM038.contigs.fa.gz',
 'TDM013': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM013.contigs.fa.gz',
 'TDM034': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM034.contigs.fa.gz',
 'TDM040': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM040.contigs.fa.gz',
 'EXB080_A1201': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A1201.contigs.fa.gz',
 'TDM002': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM002.contigs.fa.gz',
 'TDM048': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM048.contigs.fa.gz',
 'TDM060': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM060.contigs.fa.gz',
 'TDM055': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM055.contigs.fa.gz',
 'TDM017': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM017.contigs.fa.gz',
 'TDM004': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM004.contigs.fa.gz',
 'TDM022': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM022.contigs.fa.gz',
 'TDM044': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM044.contigs.fa.gz',
 'TDM052': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM052.contigs.fa.gz',
 'EXB080_A0901': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A0901.contigs.fa.gz',
 'TDM041': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM041.contigs.fa.gz',
 'TDM059': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM059.contigs.fa.gz',
 'TDM001': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM001.contigs.fa.gz',
 'TDM037': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM037.contigs.fa.gz',
 'TDM019': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM019.contigs.fa.gz',
 'TDM026': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM026.contigs.fa.gz',
 'TDM033': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM033.contigs.fa.gz',
 'TDM046': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM046.contigs.fa.gz',
 'TDM050': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM050.contigs.fa.gz',
 'EXB080_A1401': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-EXB080_A1401.contigs.fa.gz',
 'TDM058': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM058.contigs.fa.gz',
 'TDM029': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM029.contigs.fa.gz',
 'TDM018': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM018.contigs.fa.gz',
 'TDM030': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM030.contigs.fa.gz',
 'TDM047': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM047.contigs.fa.gz',
 'TDM015': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM015.contigs.fa.gz',
 'TDM053': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM053.contigs.fa.gz',
 'TDM011': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM011.contigs.fa.gz',
 'TDM051': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM051.contigs.fa.gz',
 'TDM045': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM045.contigs.fa.gz',
 'TDM008': '/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/MEGAHIT-group-TDM008.contigs.fa.gz'}

In [ ]:
outdir = "<path to>/damage_inference_core/fasta"

In [126]:
for g in tqdm(core_df.genus.unique()):
    for s in core_df['sample'].unique():
        try:
            create_fasta(core_df, s, g, assemblies_dict[s], outdir)
        except:
            print(f"Error with {g} {s}")

100%|██████████| 6/6 [04:17<00:00, 42.91s/it]

### Prepare sample sheets for nf-damage inference pipeline

In [26]:
b = list(Path("/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/").rglob("*.bam"))
b

[PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM039/MEGAHIT-group-TDM039-TDM039_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM042/MEGAHIT-group-TDM042-TDM042_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A0102/MEGAHIT-group-EXB080_A0102-EXB080_A0102.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM003/MEGAHIT-group-TDM003-TDM003_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM011/MEGAHIT-group-TDM011-TDM011_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM004/MEGAHIT-group-TDM004-TDM004_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM014/MEGAHIT-group-TDM014-TDM014_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM051/MEGAHIT-group-TDM051-TDM051_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A0801/MEGAHIT-group-EXB080_A0801-EXB080_A0801.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM060/MEGAHIT-group-TDM060-TDM060_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A1001/MEGAHIT-group-EXB080_A1001-EXB080_A1001.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM041/MEGAHIT-group-TDM041-TDM041_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A0101/MEGAHIT-group-EXB080_A0101-EXB080_A0101.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM031/MEGAHIT-group-TDM031-TDM031_A0501.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM030/MEGAHIT-group-TDM030-TDM030_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM043/MEGAHIT-group-TDM043-TDM043_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM044/MEGAHIT-group-TDM044-TDM044_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM018/MEGAHIT-group-TDM018-TDM018_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM016/MEGAHIT-group-TDM016-TDM016_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A1301/MEGAHIT-group-EXB080_A1301-EXB080_A1301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM049/MEGAHIT-group-TDM049-TDM049_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM027/MEGAHIT-group-TDM027-TDM027_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM053/MEGAHIT-group-TDM053-TDM053_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM054/MEGAHIT-group-TDM054-TDM054_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A0901/MEGAHIT-group-EXB080_A0901-EXB080_A0901.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM046/MEGAHIT-group-TDM046-TDM046_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM057/MEGAHIT-group-TDM057-TDM057_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM058/MEGAHIT-group-TDM058-TDM058_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM050/MEGAHIT-group-TDM050-TDM050_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM036/MEGAHIT-group-TDM036-TDM036_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM001/MEGAHIT-group-TDM001-TDM001_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM029/MEGAHIT-group-TDM029-TDM029_A0501.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM005/MEGAHIT-group-TDM005-TDM005_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM015/MEGAHIT-group-TDM015-TDM015_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM028/MEGAHIT-group-TDM028-TDM028_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM021/MEGAHIT-group-TDM021-TDM021_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM020/MEGAHIT-group-TDM020-TDM020_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM002/MEGAHIT-group-TDM002-TDM002_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM010/MEGAHIT-group-TDM010-TDM010_A0501.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM019/MEGAHIT-group-TDM019-TDM019_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM025/MEGAHIT-group-TDM025-TDM025_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM013/MEGAHIT-group-TDM013-TDM013_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM012/MEGAHIT-group-TDM012-TDM012_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM006/MEGAHIT-group-TDM006-TDM006_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM061/MEGAHIT-group-TDM061-TDM061_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM008/MEGAHIT-group-TDM008-TDM008_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM035/MEGAHIT-group-TDM035-TDM035_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM045/MEGAHIT-group-TDM045-TDM045_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM023/MEGAHIT-group-TDM023-TDM023_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM024/MEGAHIT-group-TDM024-TDM024_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM022/MEGAHIT-group-TDM022-TDM022_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM007/MEGAHIT-group-TDM007-TDM007_A0201.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM055/MEGAHIT-group-TDM055-TDM055_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM052/MEGAHIT-group-TDM052-TDM052_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM017/MEGAHIT-group-TDM017-TDM017_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM047/MEGAHIT-group-TDM047-TDM047_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM048/MEGAHIT-group-TDM048-TDM048_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A1101/MEGAHIT-group-EXB080_A1101-EXB080_A1101.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM040/MEGAHIT-group-TDM040-TDM040_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM026/MEGAHIT-group-TDM026-TDM026_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A1401/MEGAHIT-group-EXB080_A1401-EXB080_A1401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM037/MEGAHIT-group-TDM037-TDM037_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM038/MEGAHIT-group-TDM038-TDM038_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM033/MEGAHIT-group-TDM033-TDM033_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM059/MEGAHIT-group-TDM059-TDM059_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM034/MEGAHIT-group-TDM034-TDM034_A0401.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM032/MEGAHIT-group-TDM032-TDM032_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-TDM056/MEGAHIT-group-TDM056-TDM056_A0301.bam'),
 PosixPath('/mnt/archgen/users/borry/18_speleothem/results/nf-coreMAG/Assembly/MEGAHIT/QC/group-EXB080_A1201/MEGAHIT-group-EXB080_A1201-EXB080_A1201.bam')]

In [ ]:
pd.DataFrame({
    "sample": [i.stem.split("-")[2] for i in b],
    "bam": [i.as_posix() for i in b]
}).to_csv("<path to>/damage_inference_core/bams.csv", index=False)

In [ ]:
f = list(Path("<path to>/damage_inference_core/fasta").glob("*.fa"))
f

[PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM033_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM042_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/EXB080_A0901_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/EXB080_A0801_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM056_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM030_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM001_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM038_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM051_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM017_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM019_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM055_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM036_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM003_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM037_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM027_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM013_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM053_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM052_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM060_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM049_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM005_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM043_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM014_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM023_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM015_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM054_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM024_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM007_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM034_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM016_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM008_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM012_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM022_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM035_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM006_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM057_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM010_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM045_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM028_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM025_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM046_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM020_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM061_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM011_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM039_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM031_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM002_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM029_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM004_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM021_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM040_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM044_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM048_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM018_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM026_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM041_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM032_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM059_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM047_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM050_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM058_nitrospira.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM033_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM042_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM056_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM030_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM001_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM038_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM051_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM017_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM019_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM055_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM036_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM003_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM037_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM027_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM013_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM053_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM052_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM060_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM049_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM005_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM014_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM023_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM015_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM054_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM024_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM007_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM034_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM016_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM008_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM012_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM022_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM035_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM006_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM010_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM045_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM028_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM025_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM046_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM020_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM011_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM039_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM031_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM002_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM029_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM004_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM021_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM040_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM048_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM018_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM026_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM041_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM032_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM059_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM047_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM050_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM058_conexibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM033_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM042_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM030_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM001_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM038_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM051_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM017_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM019_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM036_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM003_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM037_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM027_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM013_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM053_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM052_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM060_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM049_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM005_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM014_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM015_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM054_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM024_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM007_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM034_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM016_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM008_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM012_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM022_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM035_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM006_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM057_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM010_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM045_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM028_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM025_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM046_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM020_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM061_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM011_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM039_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM031_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM002_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM029_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM004_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM021_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM040_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM044_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM048_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM018_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM026_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM041_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM032_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM059_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM047_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM050_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM058_piscinibacter.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM033_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM042_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM056_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM030_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM001_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM038_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM051_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM017_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM019_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM055_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM036_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM003_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM037_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM027_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM013_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM053_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM052_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM060_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM049_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM005_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM014_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM023_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM015_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM054_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM024_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM007_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM034_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM016_candidatus_nitrosotenuis.fa'),
 PosixPath('/home/lucia_winkler/speleothem/damage_inference_core/fasta/TDM012_candidatus_nitrosotenuis.fa'),

In [131]:
samples = [i.stem.split("_")[0] for i in f]
genera = ["_".join(i.stem.split("_")[1:]) for i in f]
fa = [i.as_posix() for i in f]

In [ ]:
pd.DataFrame({
    "sample": samples,
    "taxon": genera,
    "genome": fa
    }).to_csv("<path to>/damage_inference_core/genomes.csv", index=False)

## Select genera for model testing
Here I focus on the genera present in 50-54/60 of the stalagmite datasets

In [28]:
test_genera = na_counts[(na_counts >= 6) & (na_counts <= 10)].index.tolist()

test_genera

['Desertibaculum',
 'Immundisolibacter',
 'Nitrosopumilus',
 'Nitrosospira',
 'Sulfuricaulis',
 'Sulfuritalea']

In [29]:
test_df= filtered_df[filtered_df['genus'].isin(test_genera)]

test_df.groupby(['sample','genus'])['contig'].count().unstack(fill_value=0)

genus,Desertibaculum,Immundisolibacter,Nitrosopumilus,Nitrosospira,Sulfuricaulis,Sulfuritalea
sample,,,,,,
TDM001,1,3,2,0,2,8
TDM002,1,2,4,0,2,4
TDM003,2,1,3,1,2,5
TDM004,2,1,8,1,2,4
TDM005,5,2,18,1,1,7
TDM006,0,2,1,1,0,1
TDM007,1,2,1,1,1,1
TDM008,2,2,1,1,2,6
TDM010,2,2,3,2,1,4
TDM011,0,2,2,2,2,3
TDM012,0,0,2,0,1,0
TDM013,2,1,4,2,2,5
TDM014,2,1,2,0,1,6
TDM015,0,4,1,2,9,3
TDM016,0,1,12,3,10,4
TDM017,4,0,2,1,10,3
TDM018,1,1,0,2,7,3
TDM019,0,1,42,1,4,6
TDM020,2,2,37,1,1,4
TDM021,1,2,37,1,4,7
TDM022,3,3,58,2,6,4
TDM023,1,0,48,3,1,2
TDM024,0,1,89,4,2,1
TDM025,2,2,2,1,4,7
TDM026,1,1,10,4,0,4
TDM027,2,1,10,2,1,5
TDM028,1,3,16,3,4,7
TDM029,4,5,7,2,6,13
TDM030,2,2,11,0,1,13
TDM031,4,3,10,0,8,13
TDM032,3,4,1,2,4,10
TDM033,3,4,1,2,2,6
TDM034,3,3,101,3,9,7
TDM035,8,3,83,3,7,12
TDM036,2,3,68,3,4,4
TDM037,5,2,81,8,8,10
TDM038,5,4,16,2,11,15
TDM039,3,2,11,3,3,5
TDM040,6,1,7,2,4,5
TDM041,3,1,6,3,6,4
TDM042,2,3,22,5,4,8
TDM043,0,0,1,0,0,0
TDM044,0,0,1,2,0,0
TDM045,9,2,12,5,7,13
TDM046,6,2,24,5,10,12
TDM047,6,1,6,2,3,13
TDM048,5,1,8,8,10,11
TDM049,5,2,2,1,7,9
TDM050,2,2,6,6,6,7
TDM051,6,3,6,3,9,12
TDM052,2,5,16,5,10,9
TDM053,1,2,12,5,5,7
TDM054,2,3,16,2,3,6
TDM055,2,2,2,4,0,3
TDM056,1,2,4,5,1,0
TDM057,1,2,0,1,0,0
TDM058,0,1,0,1,0,0
TDM059,1,2,0,2,0,0
TDM060,1,1,0,2,0,0
TDM061,1,0,0,1,0,0

In [ ]:
outdir = "<path to>/damage_inference_model_testing/fasta"
for g in tqdm(test_df.genus.unique()):
    for s in test_df['sample'].unique():
        try:
            create_fasta(test_df, s, g, assemblies_dict[s], outdir)
        except:
            print(f"Error with {g} {s}")

100%|██████████| 6/6 [02:45<00:00, 27.63s/it]

In [ ]:
pd.DataFrame({
    "sample": [i.stem.split("-")[2] for i in b],
    "bam": [i.as_posix() for i in b]
}).to_csv("<path to>/damage_inference_model_testing/bams.csv", index=False)

In [ ]:
f = list(Path("<path to>/damage_inference_model_testing/fasta").glob("*.fa"))
f

samples = [i.stem.split("_")[0] for i in f]
genera = ["_".join(i.stem.split("_")[1:]) for i in f]
fa = [i.as_posix() for i in f]

pd.DataFrame({
    "sample": samples,
    "taxon": genera,
    "genome": fa
    }).to_csv("<path to>/damage_inference_model_testing/genomes.csv", index=False)